export const GET_LANGUAGES = "GET_LANGUAGES";
export const SET_LANGUAGES = "SET_LANGUAGES";

export const GET_TOPIC_CODES = "GET_TOPIC_CODES";
export const SET_TOPIC_CODES = "SET_TOPIC_CODES";

export const SET_CHANNEL = "SET_CHANNEL";
export const GET_CHANNEL = "GET_CHANNEL";

export const GET_DESTINATIONS = "GET_DESTINATIONS";
export const SET_DESTINATIONS = "SET_DESTINATIONS";

export const SET_FILTERS = "SET_FILTERS";

export const GET_SEARCH_RESULT = "GET_SEARCH_RESULT";
export const SET_SEARCH_RESULT =  "SET_SEARCH_RESULT";

export const GET_SINGLE_RECORD = "GET_SINGLE_RECORD";
export const SET_SINGLE_RECORD = "SET_SINGLE_RECORD";

export const SET_DOWNLOAD_LINK = "SET_DOWNLOAD_LINK";
export const GET_DOWNLOAD_LINK = "GET_DOWNLOAD_LINK";

export const GET_EXPORT_LINK =  "GET_EXPORT_LINK";